### ISSUE TITLE
metadata clarification

### ISSUE THREAD

**Issue by hurleyLi** [Yale73/scRNA-seq-for-diverse-human-rashes#1]
Hi! Very nice paper! I'm wondering if you could help clarify one of the metadata columns in the released file (`Manuscript_Object.rds`). There's one column called "treat" in the metadata. Does that column mean "treatment"? I saw 2 AD, 3 CIR, and 2 PsO patients have "yes" under "treat". Could you please specify what kind of treatment have they received? I couldn't find that information in the paper. 

Thanks!
Hurley

**Comment by Yale73** [comment]
Hi Hurley,

Thanks for your interest and sorry for the late reply. I should apologize that the "treat" is misleading.  The 'treat' means some patients have special systemic treatment because of other diseases, e.g., one psoriasis patient has mycophenolate and cyclosporine for a liver transplant. The "treat" also means some CIR patients were offered a trial on the IL4Ra-blocking treatment with dupilumab after biopsy. It's our own annotation and you can ignore it.

Please feel free to let me know if you have other questions.

Best,
Yale
________________________________
From: Hurley ***@***.***>
Sent: Monday, May 23, 2022 11:07 AM
To: Yale73/scRNA-seq-for-diverse-human-rashes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Yale73/scRNA-seq-for-diverse-human-rashes] metadata clarification (Issue #1)

Hi! Very nice paper! I'm wondering if you could help clarify one of the metadata columns in the released file (Manuscript_Object.rds). There's one column called "treat" in the metadata. Does that column mean "treatment"? I saw 2 AD, 3 CIR,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Hi! Very nice paper! I'm wondering if you could help clarify one of the metadata columns in the released file (Manuscript_Object.rds). There's one column called "treat" in the metadata. Does that column mean "treatment"? I saw 2 AD, 3 CIR, and 2 PsO patients have "yes" under "treat". Could you please specify what kind of treatment have they received? I couldn't find that information in the paper.

Thanks!
Hurley

**Comment by hurleyLi** [comment]
Thanks for the clarification Yale!
